combineCmdLine.o: combineCmdLine.cpp combineKmers.hpp gzstream/gzstream.h
combineInit.o: combineInit.cpp combineKmers.hpp gzstream/gzstream.h
combineKmers.o: combineKmers.cpp combineKmers.hpp gzstream/gzstream.h
configuration.o: configuration.cpp configuration.h input_reader.h
fsm-lite-anterior.o: fsm-lite-anterior.cpp default.h configuration.h \
 input_reader.h /home/joyce.souza/include/sdsl/suffix_trees.hpp \
 /home/joyce.souza/include/sdsl/cst_sct3.hpp \
 /home/joyce.souza/include/sdsl/int_vector.hpp \
 /home/joyce.souza/include/sdsl/bits.hpp \
 /home/joyce.souza/include/sdsl/structure_tree.hpp \
 /home/joyce.souza/include/sdsl/uintx_t.hpp \
 /home/joyce.souza/include/sdsl/config.hpp \
 /home/joyce.souza/include/sdsl/util.hpp \
 /home/joyce.souza/include/sdsl/sfstream.hpp \
 /home/joyce.souza/include/sdsl/ram_fs.hpp \
 /home/joyce.souza/include/sdsl/ram_filebuf.hpp \
 /home/joyce.souza/include/sdsl/ram_fs.hpp \
 /home/joyce.souza/include/sdsl/io.hpp \
 /home/joyce.souza/include/sdsl/sdsl_concepts.hpp \
 /home/joyce.souza/include/sdsl/memory_management.hpp \
 /home/joyce.souza/include/sdsl/int_vector_buffer.hpp \
 /home/joyce.souza/include/sdsl/iterators.hpp \
 /home/joyce.souza/include/sdsl/lcp.hpp \
 /home/joyce.souza/include/sdsl/csa_alphabet_strategy.hpp \
 /home/joyce.souza/include/sdsl/sd_vector.hpp \
 /home/joyce.souza/include/sdsl/select_support_mcl.hpp \
 /home/joyce.souza/include/sdsl/select_support.hpp \
 /home/joyce.souza/include/sdsl/rank_support.hpp \
 /home/joyce.souza/include/sdsl/rank_support_v.hpp \
 /home/joyce.souza/include/sdsl/rank_support_v5.hpp \
 /home/joyce.souza/include/sdsl/rank_support_scan.hpp \
 /home/joyce.souza/include/sdsl/select_support_scan.hpp \
 /home/joyce.souza/include/sdsl/construct_isa.hpp \
 /home/joyce.souza/include/sdsl/lcp_support_sada.hpp \
 /home/joyce.souza/include/sdsl/csa_sada.hpp \
 /home/joyce.souza/include/sdsl/enc_vector.hpp \
 /home/joyce.souza/include/sdsl/coder.hpp \
 /home/joyce.souza/include/sdsl/coder_fibonacci.hpp \
 /home/joyce.souza/include/sdsl/coder_elias_delta.hpp \
 /home/joyce.souza/include/sdsl/coder_elias_gamma.hpp \
 /home/joyce.souza/include/sdsl/coder_comma.hpp \
 /home/joyce.souza/include/sdsl/bits.hpp \
 /home/joyce.souza/include/sdsl/suffix_array_helper.hpp \
 /home/joyce.souza/include/sdsl/csa_sampling_strategy.hpp \
 /home/joyce.souza/include/sdsl/inv_perm_support.hpp \
 /home/joyce.souza/include/sdsl/bit_vectors.hpp \
 /home/joyce.souza/include/sdsl/bit_vector_il.hpp \
 /home/joyce.souza/include/sdsl/rrr_vector.hpp \
 /home/joyce.souza/include/sdsl/rrr_helper.hpp \
 /home/joyce.souza/include/sdsl/uint128_t.hpp \
 /home/joyce.souza/include/sdsl/uint256_t.hpp \
 /home/joyce.souza/include/sdsl/rrr_vector_15.hpp \
 /home/joyce.souza/include/sdsl/hyb_vector.hpp \
 /home/joyce.souza/include/sdsl/wavelet_trees.hpp \
 /home/joyce.souza/include/sdsl/wt_pc.hpp \
 /home/joyce.souza/include/sdsl/wt_helper.hpp \
 /home/joyce.souza/include/sdsl/wt_blcd.hpp \
 /home/joyce.souza/include/sdsl/wt_gmr.hpp \
 /home/joyce.souza/include/sdsl/bit_vectors.hpp \
 /home/joyce.souza/include/sdsl/int_vector.hpp \
 /home/joyce.souza/include/sdsl/vectors.hpp \
 /home/joyce.souza/include/sdsl/vlc_vector.hpp \
 /home/joyce.souza/include/sdsl/dac_vector.hpp \
 /home/joyce.souza/include/sdsl/wt_huff.hpp \
 /home/joyce.souza/include/sdsl/wt_hutu.hpp \
 /home/joyce.souza/include/sdsl/wt_int.hpp \
 /home/joyce.souza/include/sdsl/wm_int.hpp \
 /home/joyce.souza/include/sdsl/wt_rlmn.hpp \
 /home/joyce.souza/include/sdsl/wt_ap.hpp \
 /home/joyce.souza/include/sdsl/construct.hpp \
 /home/joyce.souza/include/sdsl/construct_lcp.hpp \
 /home/joyce.souza/include/sdsl/construct_bwt.hpp \
 /home/joyce.souza/include/sdsl/wt_algorithm.hpp \
 /home/joyce.souza/include/sdsl/construct_lcp_helper.hpp \
 /home/joyce.souza/include/sdsl/construct_sa.hpp \
 /home/joyce.souza/include/divsufsort.h \
 /home/joyce.souza/include/divsufsort64.h \
 /home/joyce.souza/include/sdsl/qsufsort.hpp \
 /home/joyce.souza/include/sdsl/construct_sa_se.hpp \
 /home/joyce.souza/include/sdsl/construct_config.hpp \
 /home/joyce.souza/include/sdsl/lcp_byte.hpp \
 /home/joyce.souza/include/sdsl/lcp_wt.hpp \
 /home/joyce.souza/include/sdsl/lcp_vlc.hpp \
 /home/joyce.souza/include/sdsl/lcp_dac.hpp \
 /home/joyce.souza/include/sdsl/vectors.hpp \
 /home/joyce.souza/include/sdsl/lcp_bitcompressed.hpp \
 /home/joyce.souza/include/sdsl/lcp_support_tree.hpp \
 /home/joyce.souza/include/sdsl/lcp_support_tree2.hpp \
 /home/joyce.souza/include/sdsl/sorted_multi_stack_support.hpp \
 /home/joyce.souza/include/sdsl/bp_support.hpp \
 /home/joyce.souza/include/sdsl/bp_support_g.hpp \
 /home/joyce.souza/include/sdsl/nearest_neighbour_dictionary.hpp \
 /home/joyce.souza/include/sdsl/rmq_support.hpp \
 /home/joyce.souza/include/sdsl/rmq_support_sparse_table.hpp \
 /home/joyce.souza/include/sdsl/rmq_succinct_sct.hpp \
 /home/joyce.souza/include/sdsl/bp_support_sada.hpp \
 /home/joyce.souza/include/sdsl/bp_support_algorithm.hpp \
 /home/joyce.souza/include/sdsl/sorted_stack_support.hpp \
 /home/joyce.souza/include/sdsl/fast_cache.hpp \
 /home/joyce.souza/include/sdsl/suffix_tree_helper.hpp \
 /home/joyce.souza/include/sdsl/rmq_succinct_sada.hpp \
 /home/joyce.souza/include/sdsl/bp_support_gg.hpp \
 /home/joyce.souza/include/sdsl/csa_wt.hpp \
 /home/joyce.souza/include/sdsl/cst_iterators.hpp \
 /home/joyce.souza/include/sdsl/suffix_tree_algorithm.hpp \
 /home/joyce.souza/include/sdsl/suffix_array_algorithm.hpp \
 /home/joyce.souza/include/sdsl/cst_sada.hpp \
 /home/joyce.souza/include/sdsl/cst_fully.hpp \
 /home/joyce.souza/include/sdsl/suffix_arrays.hpp \
 /home/joyce.souza/include/sdsl/csa_bitcompressed.hpp \
 /home/joyce.souza/include/sdsl/wt_algorithm.hpp
fsm-lite-mod2.o: fsm-lite-mod2.cpp default.h configuration.h \
 input_reader.h /home/joyce.souza/include/sdsl/suffix_trees.hpp \
 /home/joyce.souza/include/sdsl/cst_sct3.hpp \
 /home/joyce.souza/include/sdsl/int_vector.hpp \
 /home/joyce.souza/include/sdsl/bits.hpp \
 /home/joyce.souza/include/sdsl/structure_tree.hpp \
 /home/joyce.souza/include/sdsl/uintx_t.hpp \
 /home/joyce.souza/include/sdsl/config.hpp \
 /home/joyce.souza/include/sdsl/util.hpp \
 /home/joyce.souza/include/sdsl/sfstream.hpp \
 /home/joyce.souza/include/sdsl/ram_fs.hpp \
 /home/joyce.souza/include/sdsl/ram_filebuf.hpp \
 /home/joyce.souza/include/sdsl/ram_fs.hpp \
 /home/joyce.souza/include/sdsl/io.hpp \
 /home/joyce.souza/include/sdsl/sdsl_concepts.hpp \
 /home/joyce.souza/include/sdsl/memory_management.hpp \
 /home/joyce.souza/include/sdsl/int_vector_buffer.hpp \
 /home/joyce.souza/include/sdsl/iterators.hpp \
 /home/joyce.souza/include/sdsl/lcp.hpp \
 /home/joyce.souza/include/sdsl/csa_alphabet_strategy.hpp \
 /home/joyce.souza/include/sdsl/sd_vector.hpp \
 /home/joyce.souza/include/sdsl/select_support_mcl.hpp \
 /home/joyce.souza/include/sdsl/select_support.hpp \
 /home/joyce.souza/include/sdsl/rank_support.hpp \
 /home/joyce.souza/include/sdsl/rank_support_v.hpp \
 /home/joyce.souza/include/sdsl/rank_support_v5.hpp \
 /home/joyce.souza/include/sdsl/rank_support_scan.hpp \
 /home/joyce.souza/include/sdsl/select_support_scan.hpp \
 /home/joyce.souza/include/sdsl/construct_isa.hpp \
 /home/joyce.souza/include/sdsl/lcp_support_sada.hpp \
 /home/joyce.souza/include/sdsl/csa_sada.hpp \
 /home/joyce.souza/include/sdsl/enc_vector.hpp \
 /home/joyce.souza/include/sdsl/coder.hpp \
 /home/joyce.souza/include/sdsl/coder_fibonacci.hpp \
 /home/joyce.souza/include/sdsl/coder_elias_delta.hpp \
 /home/joyce.souza/include/sdsl/coder_elias_gamma.hpp \
 /home/joyce.souza/include/sdsl/coder_comma.hpp \
 /home/joyce.souza/include/sdsl/bits.hpp \
 /home/joyce.souza/include/sdsl/suffix_array_helper.hpp \
 /home/joyce.souza/include/sdsl/csa_sampling_strategy.hpp \
 /home/joyce.souza/include/sdsl/inv_perm_support.hpp \
 /home/joyce.souza/include/sdsl/bit_vectors.hpp \
 /home/joyce.souza/include/sdsl/bit_vector_il.hpp \
 /home/joyce.souza/include/sdsl/rrr_vector.hpp \
 /home/joyce.souza/include/sdsl/rrr_helper.hpp \
 /home/joyce.souza/include/sdsl/uint128_t.hpp \
 /home/joyce.souza/include/sdsl/uint256_t.hpp \
 /home/joyce.souza/include/sdsl/rrr_vector_15.hpp \
 /home/joyce.souza/include/sdsl/hyb_vector.hpp \
 /home/joyce.souza/include/sdsl/wavelet_trees.hpp \
 /home/joyce.souza/include/sdsl/wt_pc.hpp \
 /home/joyce.souza/include/sdsl/wt_helper.hpp \
 /home/joyce.souza/include/sdsl/wt_blcd.hpp \
 /home/joyce.souza/include/sdsl/wt_gmr.hpp \
 /home/joyce.souza/include/sdsl/bit_vectors.hpp \
 /home/joyce.souza/include/sdsl/int_vector.hpp \
 /home/joyce.souza/include/sdsl/vectors.hpp \
 /home/joyce.souza/include/sdsl/vlc_vector.hpp \
 /home/joyce.souza/include/sdsl/dac_vector.hpp \
 /home/joyce.souza/include/sdsl/wt_huff.hpp \
 /home/joyce.souza/include/sdsl/wt_hutu.hpp \
 /home/joyce.souza/include/sdsl/wt_int.hpp \
 /home/joyce.souza/include/sdsl/wm_int.hpp \
 /home/joyce.souza/include/sdsl/wt_rlmn.hpp \
 /home/joyce.souza/include/sdsl/wt_ap.hpp \
 /home/joyce.souza/include/sdsl/construct.hpp \
 /home/joyce.souza/include/sdsl/construct_lcp.hpp \
 /home/joyce.souza/include/sdsl/construct_bwt.hpp \
 /home/joyce.souza/include/sdsl/wt_algorithm.hpp \
 /home/joyce.souza/include/sdsl/construct_lcp_helper.hpp \
 /home/joyce.souza/include/sdsl/construct_sa.hpp \
 /home/joyce.souza/include/divsufsort.h \
 /home/joyce.souza/include/divsufsort64.h \
 /home/joyce.souza/include/sdsl/qsufsort.hpp \
 /home/joyce.souza/include/sdsl/construct_sa_se.hpp \
 /home/joyce.souza/include/sdsl/construct_config.hpp \
 /home/joyce.souza/include/sdsl/lcp_byte.hpp \
 /home/joyce.souza/include/sdsl/lcp_wt.hpp \
 /home/joyce.souza/include/sdsl/lcp_vlc.hpp \
 /home/joyce.souza/include/sdsl/lcp_dac.hpp \
 /home/joyce.souza/include/sdsl/vectors.hpp \
 /home/joyce.souza/include/sdsl/lcp_bitcompressed.hpp \
 /home/joyce.souza/include/sdsl/lcp_support_tree.hpp \
 /home/joyce.souza/include/sdsl/lcp_support_tree2.hpp \
 /home/joyce.souza/include/sdsl/sorted_multi_stack_support.hpp \
 /home/joyce.souza/include/sdsl/bp_support.hpp \
 /home/joyce.souza/include/sdsl/bp_support_g.hpp \
 /home/joyce.souza/include/sdsl/nearest_neighbour_dictionary.hpp \
 /home/joyce.souza/include/sdsl/rmq_support.hpp \
 /home/joyce.souza/include/sdsl/rmq_support_sparse_table.hpp \
 /home/joyce.souza/include/sdsl/rmq_succinct_sct.hpp \
 /home/joyce.souza/include/sdsl/bp_support_sada.hpp \
 /home/joyce.souza/include/sdsl/bp_support_algorithm.hpp \
 /home/joyce.souza/include/sdsl/sorted_stack_support.hpp \
 /home/joyce.souza/include/sdsl/fast_cache.hpp \
 /home/joyce.souza/include/sdsl/suffix_tree_helper.hpp \
 /home/joyce.souza/include/sdsl/rmq_succinct_sada.hpp \
 /home/joyce.souza/include/sdsl/bp_support_gg.hpp \
 /home/joyce.souza/include/sdsl/csa_wt.hpp \
 /home/joyce.souza/include/sdsl/cst_iterators.hpp \
 /home/joyce.souza/include/sdsl/suffix_tree_algorithm.hpp \
 /home/joyce.souza/include/sdsl/suffix_array_algorithm.hpp \
 /home/joyce.souza/include/sdsl/cst_sada.hpp \
 /home/joyce.souza/include/sdsl/cst_fully.hpp \
 /home/joyce.souza/include/sdsl/suffix_arrays.hpp \
 /home/joyce.souza/include/sdsl/csa_bitcompressed.hpp \
 /home/joyce.souza/include/sdsl/wt_algorithm.hpp
fsm-lite.o: fsm-lite.cpp default.h configuration.h input_reader.h \
 /home/joyce.souza/include/sdsl/suffix_trees.hpp \
 /home/joyce.souza/include/sdsl/cst_sct3.hpp \
 /home/joyce.souza/include/sdsl/int_vector.hpp \
 /home/joyce.souza/include/sdsl/bits.hpp \
 /home/joyce.souza/include/sdsl/structure_tree.hpp \
 /home/joyce.souza/include/sdsl/uintx_t.hpp \
 /home/joyce.souza/include/sdsl/config.hpp \
 /home/joyce.souza/include/sdsl/util.hpp \
 /home/joyce.souza/include/sdsl/sfstream.hpp \
 /home/joyce.souza/include/sdsl/ram_fs.hpp \
 /home/joyce.souza/include/sdsl/ram_filebuf.hpp \
 /home/joyce.souza/include/sdsl/ram_fs.hpp \
 /home/joyce.souza/include/sdsl/io.hpp \
 /home/joyce.souza/include/sdsl/sdsl_concepts.hpp \
 /home/joyce.souza/include/sdsl/memory_management.hpp \
 /home/joyce.souza/include/sdsl/int_vector_buffer.hpp \
 /home/joyce.souza/include/sdsl/iterators.hpp \
 /home/joyce.souza/include/sdsl/lcp.hpp \
 /home/joyce.souza/include/sdsl/csa_alphabet_strategy.hpp \
 /home/joyce.souza/include/sdsl/sd_vector.hpp \
 /home/joyce.souza/include/sdsl/select_support_mcl.hpp \
 /home/joyce.souza/include/sdsl/select_support.hpp \
 /home/joyce.souza/include/sdsl/rank_support.hpp \
 /home/joyce.souza/include/sdsl/rank_support_v.hpp \
 /home/joyce.souza/include/sdsl/rank_support_v5.hpp \
 /home/joyce.souza/include/sdsl/rank_support_scan.hpp \
 /home/joyce.souza/include/sdsl/select_support_scan.hpp \
 /home/joyce.souza/include/sdsl/construct_isa.hpp \
 /home/joyce.souza/include/sdsl/lcp_support_sada.hpp \
 /home/joyce.souza/include/sdsl/csa_sada.hpp \
 /home/joyce.souza/include/sdsl/enc_vector.hpp \
 /home/joyce.souza/include/sdsl/coder.hpp \
 /home/joyce.souza/include/sdsl/coder_fibonacci.hpp \
 /home/joyce.souza/include/sdsl/coder_elias_delta.hpp \
 /home/joyce.souza/include/sdsl/coder_elias_gamma.hpp \
 /home/joyce.souza/include/sdsl/coder_comma.hpp \
 /home/joyce.souza/include/sdsl/bits.hpp \
 /home/joyce.souza/include/sdsl/suffix_array_helper.hpp \
 /home/joyce.souza/include/sdsl/csa_sampling_strategy.hpp \
 /home/joyce.souza/include/sdsl/inv_perm_support.hpp \
 /home/joyce.souza/include/sdsl/bit_vectors.hpp \
 /home/joyce.souza/include/sdsl/bit_vector_il.hpp \
 /home/joyce.souza/include/sdsl/rrr_vector.hpp \
 /home/joyce.souza/include/sdsl/rrr_helper.hpp \
 /home/joyce.souza/include/sdsl/uint128_t.hpp \
 /home/joyce.souza/include/sdsl/uint256_t.hpp \
 /home/joyce.souza/include/sdsl/rrr_vector_15.hpp \
 /home/joyce.souza/include/sdsl/hyb_vector.hpp \
 /home/joyce.souza/include/sdsl/wavelet_trees.hpp \
 /home/joyce.souza/include/sdsl/wt_pc.hpp \
 /home/joyce.souza/include/sdsl/wt_helper.hpp \
 /home/joyce.souza/include/sdsl/wt_blcd.hpp \
 /home/joyce.souza/include/sdsl/wt_gmr.hpp \
 /home/joyce.souza/include/sdsl/bit_vectors.hpp \
 /home/joyce.souza/include/sdsl/int_vector.hpp \
 /home/joyce.souza/include/sdsl/vectors.hpp \
 /home/joyce.souza/include/sdsl/vlc_vector.hpp \
 /home/joyce.souza/include/sdsl/dac_vector.hpp \
 /home/joyce.souza/include/sdsl/wt_huff.hpp \
 /home/joyce.souza/include/sdsl/wt_hutu.hpp \
 /home/joyce.souza/include/sdsl/wt_int.hpp \
 /home/joyce.souza/include/sdsl/wm_int.hpp \
 /home/joyce.souza/include/sdsl/wt_rlmn.hpp \
 /home/joyce.souza/include/sdsl/wt_ap.hpp \
 /home/joyce.souza/include/sdsl/construct.hpp \
 /home/joyce.souza/include/sdsl/construct_lcp.hpp \
 /home/joyce.souza/include/sdsl/construct_bwt.hpp \
 /home/joyce.souza/include/sdsl/wt_algorithm.hpp \
 /home/joyce.souza/include/sdsl/construct_lcp_helper.hpp \
 /home/joyce.souza/include/sdsl/construct_sa.hpp \
 /home/joyce.souza/include/divsufsort.h \
 /home/joyce.souza/include/divsufsort64.h \
 /home/joyce.souza/include/sdsl/qsufsort.hpp \
 /home/joyce.souza/include/sdsl/construct_sa_se.hpp \
 /home/joyce.souza/include/sdsl/construct_config.hpp \
 /home/joyce.souza/include/sdsl/lcp_byte.hpp \
 /home/joyce.souza/include/sdsl/lcp_wt.hpp \
 /home/joyce.souza/include/sdsl/lcp_vlc.hpp \
 /home/joyce.souza/include/sdsl/lcp_dac.hpp \
 /home/joyce.souza/include/sdsl/vectors.hpp \
 /home/joyce.souza/include/sdsl/lcp_bitcompressed.hpp \
 /home/joyce.souza/include/sdsl/lcp_support_tree.hpp \
 /home/joyce.souza/include/sdsl/lcp_support_tree2.hpp \
 /home/joyce.souza/include/sdsl/sorted_multi_stack_support.hpp \
 /home/joyce.souza/include/sdsl/bp_support.hpp \
 /home/joyce.souza/include/sdsl/bp_support_g.hpp \
 /home/joyce.souza/include/sdsl/nearest_neighbour_dictionary.hpp \
 /home/joyce.souza/include/sdsl/rmq_support.hpp \
 /home/joyce.souza/include/sdsl/rmq_support_sparse_table.hpp \
 /home/joyce.souza/include/sdsl/rmq_succinct_sct.hpp \
 /home/joyce.souza/include/sdsl/bp_support_sada.hpp \
 /home/joyce.souza/include/sdsl/bp_support_algorithm.hpp \
 /home/joyce.souza/include/sdsl/sorted_stack_support.hpp \
 /home/joyce.souza/include/sdsl/fast_cache.hpp \
 /home/joyce.souza/include/sdsl/suffix_tree_helper.hpp \
 /home/joyce.souza/include/sdsl/rmq_succinct_sada.hpp \
 /home/joyce.souza/include/sdsl/bp_support_gg.hpp \
 /home/joyce.souza/include/sdsl/csa_wt.hpp \
 /home/joyce.souza/include/sdsl/cst_iterators.hpp \
 /home/joyce.souza/include/sdsl/suffix_tree_algorithm.hpp \
 /home/joyce.souza/include/sdsl/suffix_array_algorithm.hpp \
 /home/joyce.souza/include/sdsl/cst_sada.hpp \
 /home/joyce.souza/include/sdsl/cst_fully.hpp \
 /home/joyce.souza/include/sdsl/suffix_arrays.hpp \
 /home/joyce.souza/include/sdsl/csa_bitcompressed.hpp \
 /home/joyce.souza/include/sdsl/wt_algorithm.hpp
input_reader.o: input_reader.cpp default.h input_reader.h configuration.h
